# Generated by Django 5.2.3 on 2025-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_auth_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.TextField(default=None),
        ),
    ]
