# Generated by Django 5.2.3 on 2025-06-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_token",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
