# Generated by Django 5.2.3 on 2025-06-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_refresh_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="refresh_token",
        ),
    ]
