# Generated by Django 5.2.3 on 2025-06-16 08:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_auth_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
